version: '2'

services:

  mariadb:
    container_name: mariadb
    image: mariadb:10.0
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: pcz_production

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    image: registry.gitlab.com/projektove/projektove:latest
    command: foreman start
    volumes:
      - ruby2.1-gems:/usr/local/bundle
      - .:/app
    links: &app_links
      - mariadb:mariadb
      - redis:redis
    environment:
      # ENABLE_DEBUG_SERVER: 1
      RACK_ENV: production
      RAILS_ENV: production
      SECRET_TOKEN:
      SMTP_HOST: 0.0.0.0
      SMTP_PORT: 25
      SMTP_DOMAIN:
    # env_file: .env # Include the environment variables in the unversioned .env file
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
  ruby2.1-gems:
