version: '2'

services:
  mariadb:
    container_name: registry.gitlab.com/projektove/mariadb
    image: mariadb:10.0
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file: .env

  redis:
    container_name: registry.gitlab.com/projektove/redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data

  app:
    container_name: projektove
    image: registry.gitlab.com/projektove/projektove:latest
    command: foreman start -d /app -f Procfile.production
    volumes:
      - ./nginx:/etc/nginx
      - ./files:/app/files
      - ./log:/app/log
    depends_on:
      - redis
      - mariadb
    links: &app_links
      - mariadb:mariadb
      - redis:redis
    ports:
      - '80:80'
    env_file: .env

volumes:
  mariadb-data:
  redis-data:
